There has been a change in the method execute, in the section of code starting on line nr 270.
  
The change is in a catch statement, in a try statement, in the method ```execute```, in the class ```2```, in an initialization, in the invocation ```submitStateUpdateTask```, in the method ```updateSettings```, in the class ```MetaDataUpdateSettingsService```.
  
The following changes have been made:  
Changed type reference from ```java.lang.Exception``` to ```Throwable``` on line 270.  
